QUERIES ON SUBQUERIES
1)WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS.

-> SELECT ENAME
   FROM EMP
   WHERE SAL>(SELECT SAL
              FROM EMP
              WHERE ENAME='ADAMS');

2)WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING.

-> SELECT ENAME, SAL
   FROM EMP
   WHERE SAL<(SELECT SAL
              FROM EMP
              WHERE ENAME='KING');

3)WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES.

-> SELECT ENAME, DEPTNO
   FROM EMP
   WHERE DEPTNO=(SELECT DEPTNO
                 FROM EMP
                 WHERE ENAME='JONES');

4)WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES.

-> SELECT ENAME, JOB
   FROM EMP
   WHERE JOB = (SELECT JOB
                FROM EMP
                WHERE ENAME='JAMES');

5)WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.

->SELECT EMPNO, ENAME, SAL*12
  FROM EMP
  WHERE SAL*12>(SELECT SAL*12
              FROM EMP
              WHERE ENAME='WARD');

6)WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT.

-> SELECT ENAME, HIREDATE 
   FROM EMP
   WHERE HIREDATE<(SELECT HIREDATE
                   FROM EMP
                   WHERE ENAME='SCOTT');

7)WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT.

->SELECT ENAME, HIREDATE 
  FROM EMP
  WHERE HIREDATE>(SELECT HIREDATE
                  FROM EMP
	          WHERE JOB='PRESIDENT');

8)WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839.

->SELECT ENAME, SAL 
  FROM EMP
  WHERE SAL<(SELECT SAL
	     FROM EMP
	     WHERE EMPNO=7839);

9)WAQTD  ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER.

->SELECT *
  FROM EMP
  WHERE HIREDATE<(SELECT HIREDATE
		  FROM EMP
 		  WHERE ENAME='MILLER');

10)WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN.

->SELECT ENAME, EMPNO
  FROM EMP
  WHERE SAL>(SELECT SAL
	     FROM EMP
	     WHERE ENAME='ALLEN'); 	   

11)WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.

->SELECT ENAME, SAL
  FROM EMP
  WHERE SAL>(SELECT SAL            
             FROM EMP
             WHERE ENAME='MILLER') AND SAL<(SELECT SAL
                                            FROM EMP
                                            WHERE ENAME='ALLEN');

12)WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH.

-> SELECT *
   FROM EMP
   WHERE DEPTNO IN 20 AND JOB IN(SELECT JOB
     				 FROM EMP
     				 WHERE ENAME='SMITH');

13)WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER.

->SELECT *
  FROM EMP
  WHERE JOB IN 'MANAGER' AND DEPTNO IN(SELECT DEPTNO
                                       FROM EMP
                                       WHERE ENAME='TURNER');

14)WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING.

-> SELECT ENAME, HIREDATE
   FROM EMP
   WHERE HIREDATE>='01-JAN-1980' AND HIREDATE<(SELECT HIREDATE
                  			       FROM EMP
         				       WHERE ENAME='KING');

15)WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN 3500.

->SELECT ENAME, SAL, SAL*12
  FROM EMP
  WHERE SAL<(SELECT SAL
             FROM EMP
             WHERE ENAME='BLAKE') OR SAL>3500;

16)WAQTD ALL THE DETAILS OF EMPLOYBES WHO EARN MORE THAN SCOTT BUT LESS THAN KING.

->SELECT *
  FROM EMP
  WHERE SAL>(SELECT SAL
             FROM EMP
             WHERE ENAME='SCOTT') AND SAL<(SELECT SAL
      					   FROM EMP
     					   WHERE ENAME='KING');

17)WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE.

->SELECT ENAME 
  FROM EMP
  WHERE ENAME LIKE 'A%' AND DEPTNO IN(SELECT DEPTNO
                                      FROM EMP 
                                      WHERE ENAME='BLAKE');

18)WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH.

->SELECT ENAME, COMM
  FROM EMP
  WHERE COMM IS NOT NULL AND JOB IN(SELECT JOB
        			    FROM EMP
      				    WHERE ENAME='SMITH');

19)WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.

->SELECT *
  FROM EMP
  WHERE JOB='CLERK' AND DEPTNO IN(SELECT DEPTNO
                                  FROM EMP
                                  WHERE ENAME='TURNER');

20)WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.

->SELECT ENAME, SAL, JOB
  FROM EMP
  WHERE SAL*12>(SELECT SAL*12
            	FROM EMP
   	        WHERE ENAME='SMITH') AND SAL*12<(SELECT SAL*12
          					 FROM EMP
         					 WHERE ENAME='KING');

21)WAQTD DNAME OF THE EMPLOUYEES WHOSE NAME IS SMITH.

->SELECT DNAME
  FROM DEPT
  WHERE DEPTNO =(SELECT DEPTNO 
	         FROM EMP
                 WHERE ENAME = 'SMITH');

22)WAQTD DNAME AND LOC OF THE EMPLOYEE WHOSE ENAME IS KING.

->SELECT DNAME, LOC 
  FROM DEPT
  WHERE DEPTNO=(SELECT DEPTNO
    	        FROM EMP
   	        WHERE ENAME='KING');

23)WAQTD LOC OF THE EMP WHOSE EMPLOYEE NUMBER IS 7902.

->SELECT LOC
  FROM DEPT
  WHERE DEPTNO=(SELECT DEPTNO
                FROM EMP
      	        WHERE EMPNO = 7902);

24)WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOSE NAME ENDS WITH 'R'.

->SELECT DNAME, LOC, DEPTNO
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   WHERE ENAME LIKE '%R');

25)WAQTD DNAME OF THE EMPLOYEE WHOSE DESIGNATION IS PRESIDENT.

->SELECT DNAME
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   WHERE JOB = 'PRESIDENT');

26)WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT.

->SELECT ENAME
  FROM EMP
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM DEPT
                   WHERE DNAME = 'ACCOUNTING');

27)WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO.

->SELECT ENAME, SAL
  FROM EMP
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM DEPT
                   WHERE LOC = 'CHICAGO');

28)WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES.

->SELECT *
  FROM EMP
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM DEPT
                   WHERE DNAME = 'SALES');

29)WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF THE EMPLOYEES ARE WORKING IN NEW YORK.

->SELECT EMP.*, SAL*12 "ANNUAL SAL"
  FROM EMP
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM DEPT
                   WHERE LOC = 'NEW YORK');

30)WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT.

->SELECT ENAME
  FROM EMP
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM DEPT
                   WHERE DNAME = 'OPERATIONS');

31)WAQTD NAMES OF THE EMP EARNING MORE THAN SCOTT IN ACCOUNTING DEPT.

->SELECT ENAME
  FROM EMP
  WHERE SAL>(SELECT SAL
             FROM EMP
             WHERE ENAME = 'SCOTT') AND  DEPTNO = (SELECT DEPTNO
                                                   FROM DEPT
                                                   WHERE DNAME = 'ACCOUNTING');

32)WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO. 

->SELECT *
  FROM EMP
  WHERE JOB = 'MANAGER' AND DEPTNO = (SELECT DEPTNO
                                      FROM DEPT
                                      WHERE LOC = 'CHICAGO');

33)WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING .

->SELECT ENAME, SAL
  FROM EMP
  WHERE SAL>(SELECT SAL
             FROM EMP
             WHERE ENAME = 'KING') AND  DEPTNO = (SELECT DEPTNO
                                                  FROM DEPT
                                                  WHERE DNAME = 'ACCOUNTING');

34)WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTMENT SALES .

->SELECT *
  FROM EMP
  WHERE JOB = 'SALESMAN' AND  DEPTNO = (SELECT DEPTNO
                                        FROM DEPT
                                        WHERE DNAME = 'SALES');

35)WAQTD NAME, SAL, JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING.

->SELECT ENAME, SAL, JOB, HIREDATE
  FROM EMP
  WHERE DEPTNO = (SELECT DEPTNO
                  FROM DEPT
                  WHERE DNAME = 'OPERATIONS') AND HIREDATE < (SELECT HIREDATE
                                                              FROM EMP
                                                              WHERE ENAME = 'KING');

36)DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMENT NAME IS ENDING WITH 'S'.

->SELECT ENAME
  FROM EMP
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM DEPT
                   WHERE DNAME LIKE '%S');

37)WAQTD DNAME OF THE EMP WHOSE NAME HAS CHARACTER 'A' IN IT.

->SELECT DNAME
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   WHERE ENAME LIKE '%A%');

38)WAQTD DNAME AND LOC OF THE EMPLOYEES WHOSE SALARY IS RUPEES 800.

->SELECT DNAME, LOC
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   WHERE SAL = 800);

39)WAQTD DNAME OF THE EMPLOYEES WHO EARN COMMISSION.

->SELECT DNAME
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   WHERE COMM IS NOT NULL);

40)WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMMISSION IN DEPT 40.

->SELECT LOC
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   WHERE COMM IS NOT NULL AND DEPTNO = 40);

41)WAQTD NAME OF THE EMP EARNING MAXIMUM SALARY.

->SELECT ENAME
  FROM EMP
  WHERE SAL = (SELECT MAX(SAL)
               FROM EMP);

42)WAQTD NAME OF THE EMPLOYEE EARNING MINIMUM SALARY.

->SELECT ENAME
  FROM EMP
  WHERE SAL = (SELECT MIN(SAL)
               FROM EMP);

43)WAQTD NAME AND HIREDATE OF THE EMP HIRED BEFORE ALL TH EMPLOYEES (FIRST EMP) .

->SELECT ENAME, HIREDATE
  FROM EMP
  WHERE HIREDATE = (SELECT MIN(HIREDATE)
                    FROM EMP);

44)WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AT THE LAST.

->SELECT ENAME, HIREDATE
  FROM EMP
  WHERE HIREDATE = (SELECT MAX(HIREDATE)
                    FROM EMP);

45)WAQTD NAME, COMM OF THE EMPLOYEE WHO EARNS MIN COMMISSION.

->SELECT ENAME, COMM
  FROM EMP
  WHERE COMM = (SELECT MIN(COMM)
                FROM EMP);

46)WAQTD NAME,SAL,COMM OF THE EMPLOYEE EARNING COMMISSION.
	
->SELECT ENAME,SAL,COMM
  FROM EMP
  WHERE COMM=(SELECT MAX(COMM)
              FROM EMP);

47)WAQTD DETAILS OF EMPLOYEE WHO HAS GREATEST EMPNO.

->SELECT *
  FROM EMP
  WHERE EMPNO=(SELECT MAX(EMPNO)
               FROM EMP);

48)WAQTD DETAILS OF EMPLOYEE HAVING LEAST HIREDATE.

->SELECT *
  FROM EMP
  WHERE HIREDATE=(SELECT MIN(HIREDATE)
                  FROM EMP);

49)WAQTD DETAILS OF EMPLOYEE EARNING LEAST ANNUAL SALARY.

->SELECT *
  FROM EMP
  WHERE SAL*12=(SELECT MIN(SAL*12)
                FROM EMP);

50)WAQTD NAME,ANNUAL SALARY OF THE EMPLOYEES OF THEIR ANNUAL SALARY IS MORE THAN ALL THE SALESMAN.

->SELECT ENAME, SAL*12
  FROM EMP
  WHERE SAL*12>ALL(SELECT SAL*12
                   FROM EMP
                   WHERE JOB='SALESMAN');

51)WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN SALESMAN.

->SELECT ENAME
  FROM EMP
  WHERE SAL>ALL(SELECT SAL
                FROM EMP    
                WHERE JOB='SALESMAN');

52)WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS.

->SELECT *
 FROM EMP
 WHERE HIREDATE>ALL(SELECT HIREDATE 
                    FROM EMP
                    WHERE JOB='CLERKS');

53)WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES IF THEY ARE EARNING LESS THAN ATLEAST A MANAGER.

->SELECT ENAME,SAL
 FROM EMP
 WHERE SAL< ANY (SELECT SAL
                 FROM EMP
                 WHERE JOB='MANAGER'); 

54)WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS.

->SELECT ENAME,HIREDATE
  FROM EMP
  WHERE HIREDATE>ALL(SELECT HIREDATE
                     FROM EMP
                     WHERE JOB='MANAGER'); 

55)WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS.

->SELECT ENAME
  FROM EMP
  WHERE HIREDATE> ALL (SELECT HIREDATE
                       FROM EMP
                       WHERE JOB='MANAGER') AND SAL> ALL (SELECT SAL
                                                          FROM EMP
                                                          WHERE JOB='CLERKS'); 

56)WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEAST A SALESMAN.

->SELECT *
 FROM EMP
 WHERE HIREDATE<ANY(SELECT HIREDATE
                    FROM EMP
                    WHERE JOB='SALESMAN') AND JOB='CLERK';

57)WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT.

->SELECT *
 FROM EMP
 WHERE DEPTNO IN (SELECT DEPTNO 
                  FROM DEPT
                  WHERE DNAME='ACCOUNTING' OR DNAME='SALES');

58)WAQTD DEPARTMENT NAMES OF THE EMPLOYEES WITH NAME SMITH,KING AND MILLER.

->SELECT DNAME
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   WHERE ENAME='SMITH' OR ENAME='KING' OR ENAME='MILLER');

59)WAQTD DETAILS OF EMPLOYEES WORKING IN NEW YORK OR CHICAGO.

->SELECT*
 FROM EMP
 WHERE DEPTNO IN (SELECT DEPTNO 
                  FROM DEPT
                  WHERE LOC='NEW YORK' OR LOC='CHICAGO');

60)WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10.

->SELECT ENAME
  FROM EMP
  WHERE HIREDATE>ALL(SELECT HIREDATE
                     FROM EMP
                     WHERE DEPTNO=10);

61)WAQTD 2ND MINIMUM SALARY.

 ->SELECT MIN(SAL)
  FROM EMP
  WHERE SAL>(SELECT MIN(SAL)
             FROM EMP);

62)WAQTD 5TH MAXIMUM SALARY.

 ->SELECT MAX(SAL) FROM EMP
   WHERE SAL<(SELECT MAX(SAL) 
             FROM EMP
             WHERE SAL<(SELECT MAX(SAL) 
   	                FROM EMP
                        WHERE SAL<(SELECT MAX(SAL) 
                                   FROM EMP
                                   WHERE SAL<(SELECT MAX(SAL) 
                                              FROM EMP)))); 

63)WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY.

->SELECT ENAME
 FROM EMP
 WHERE SAL=(SELECT MAX(SAL)
            FROM EMP
            WHERE SAL<(SELECT MAX(SAL)
                       FROM EMP
                       WHERE SAL<(SELECT MAX(SAL)
                                  FROM EMP)));

64)WAQTD EMPNO OF THE EMPLOYEE EARNING 2ND MAXIMUM SALARY.

->SELECT EMPNO
  FROM EMP
  WHERE SAL=(SELECT MAX(SAL)
             FROM EMP
	     WHERE SAL<(SELECT MAX(SAL)
	                FROM EMP)); 

65)WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL.

->SELECT DNAME
 FROM DEPT
 WHERE DEPTNO=(SELECT DEPTNO
               FROM EMP
               WHERE SAL=(SELECT MAX(SAL)
                          FROM EMP
                          WHERE SAL<(SELECT MAX(SAL)
                                     FROM EMP
                                     WHERE SAL<(SELECT MAX(SAL)
                                                FROM EMP
                                                WHERE SAL<(SELECT MAX(SAL)
                                                           FROM EMP)))));

66)WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED FIRST.

->SELECT *
  FROM EMP
  WHERE HIREDATE=(SELECT MIN(HIREDATE)
                  FROM EMP
                  WHERE HIREDATE>(SELECT MIN(HIREDATE)
                                  FROM EMP));

67)WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE.

->SELECT ENAME
  FROM EMP
  WHERE HIREDATE=(SELECT MAX(HIREDATE)
                  FROM EMP
                  WHERE HIREDATE<(SELECT MAX(HIREDATE)
                                  FROM EMP));

68)WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST.

->SELECT LOC
 FROM DEPT
 WHERE DEPTNO=(SELECT DEPTNO
               FROM EMP
               WHERE HIREDATE = (SELECT MIN(HIREDATE)
                                 FROM EMP)); 

69)WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY.

->SELECT *
  FROM EMP
  WHERE SAL=(SELECT MIN(SAL)
             FROM EMP
             WHERE SAL>(SELECT MIN(SAL)
                        FROM EMP
                        WHERE SAL>(SELECT MIN(SAL)
                                   FROM EMP
                                   WHERE SAL>(SELECT MIN(SAL)
                                              FROM EMP
                                              WHERE SAL>(SELECT MIN(SAL)
                                                         FROM EMP
                                                         WHERE SAL>(SELECT MIN(SAL)
                                                                    FROM EMP
                                                                    WHERE SAL>(SELECT MIN(SAL)
                                                                               FROM EMP)))))));

70)WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY.

->SELECT DNAME
  FROM DEPT
  WHERE DEPTNO IN  (SELECT DEPTNO 
                    FROM EMP
                    WHERE SAL=(SELECT MAX(SAL)
                               FROM EMP
                               WHERE SAL<(SELECT MAX(SAL)
                                          FROM EMP)));

71)WAQTD SMITH'S REPORTING MANAGERS NAME.

->SELECT ENAME
  FROM EMP
  WHERE EMPNO=(SELECT MGR 
               FROM EMP WHERE 
               ENAME='SMITH');

72)WAQTD ADAMS MANAGERS MANAGER NAME.

->SELECT ENAME
  FROM EMP 
  WHERE EMPNO=(SELECT MGR 
               FROM EMP 
	       WHERE EMPNO =(SELECT MGR 
			     FROM EMP 
			     WHERE ENAME ='ADAMS'));

73)WAQTD DNAME OF JONES MANAGER.

->SELECT DNAME
 FROM DEPT
 WHERE DEPTNO=(SELECT DEPTNO 
	       FROM EMP
	       WHERE EMPNO=(SELECT MGR 
                            FROM EMP 
                            WHERE ENAME = 'JONES'));

74)WAQTD MILLER'S MANAGERS SALARY.

->SELECT SAL 
  FROM EMP
  WHERE EMPNO=(SELECT MGR
               FROM EMP
	       WHERE ENAME='MILLER');

75)WAQTD LOC OF SMITHS MANAGER'S MANAGER.

->SELECT LOC
  FROM DEPT
  WHERE DEPTNO=(SELECT DEPTNO
                FROM EMP
                WHERE EMPNO=(SELECT MGR
        		     FROM EMP
			     WHERE EMPNO=(SELECT MGR 
			                  FROM EMP
			                  WHERE ENAME='SMITH')));

76)WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE.

->SELECT ENAME 
  FROM EMP
  WHERE MGR=(SELECT EMPNO
	     FROM EMP
	     WHERE ENAME='BLAKE');

77)WAQTD NUMBER OF EMPLOYEES REPORTING TO KING.

->SELECT COUNT(*)
  FROM EMP
  WHERE MGR=(SELECT EMPNO
	     FROM EMP
     	     WHERE ENAME='KING');

78)WAQTD DETAILS OF EMPLOYEES REPORTING TO JONES.

->SELECT * 
  FROM EMP
  WHERE MGR=(SELECT EMPNO
 	     FROM EMP
	     WHERE ENAME='JONES');

79)WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER.

->SELECT ENAME
 FROM EMP
 WHERE EMPNO=(SELECT MGR
	      FROM EMP
	      WHERE ENAME='BLAKE');

80)WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER.

->SELECT COUNT(*)
  FROM EMP
  WHERE MGR=(SELECT EMPNO 
             FROM EMP
             WHERE ENAME='FORD');